name = "App-optex-xform"
badges = [ 'github-actions/test', 'metacpan' ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[unsupported]
os = [
    "MSWin32",
]

[FileGatherer]
exclude_match = ['^images/.*']

