---
editpanel_contextmenu:
  - item edit-changes-undo
  - item edit-changes-redo
  -
  - item edit-paste
  - item select-document
  -
  - item goto-last-edit
  - item view-dialog-find
  -
  - item file-save-current
  - item file-open
  -
  - item file-close-current

textselection_contextmenu:
  - item edit-copy
  - item edit-paste
  - item edit-replace
  - item edit-cut
  - item edit-delete
  -
  - item find-selection
  - item replace-selection
  - item tool-note-selection
  -
  - item edit-selection-comment-toggle-perl
  -
  - item edit-selection-convert-uppercase
  - item edit-selection-convert-lowercase

markermargin_contextmenu:
  -
    menu marker:
      - item marker-toggle-here
      - item marker-goto-prev-doc
      - item marker-goto-next-doc
      - item marker-goto-prev-all
      - item marker-goto-next-all
      - item marker-delete-doc
      - item marker-delete-all
  -
  -
    menu bookmark_toggle:
      - item bookmark-toggle-1
      - item bookmark-toggle-2
      - item bookmark-toggle-3
      - item bookmark-toggle-4
      - item bookmark-toggle-5
      - item bookmark-toggle-6
      - item bookmark-toggle-7
      - item bookmark-toggle-8
      - item bookmark-toggle-9
      - item bookmark-toggle-0
  -
    menu bookmark_goto:
      - item bookmark-goto-1
      - item bookmark-goto-2
      - item bookmark-goto-3
      - item bookmark-goto-4
      - item bookmark-goto-5
      - item bookmark-goto-6
      - item bookmark-goto-7
      - item bookmark-goto-8
      - item bookmark-goto-9
      - item bookmark-goto-0
  - item bookmark-delete-doc
  - item bookmark-delete-all
  -
  - item goto-line
  -
  -
    menu view_text_fold:
      - item view-editpanel-fold-toggle-here
      - item view-editpanel-fold-toggle-recursively
      - item view-editpanel-fold-toggle-level
      - item view-editpanel-fold-toggle-all
  -
  - checkitem view-editpanel-margin-marker
  - checkitem view-editpanel-margin-line-number
  - checkitem view-editpanel-margin-text-fold
  -
    menu view_textmargin:
      - radioitem view-editpanel-margin-text-0
      - radioitem view-editpanel-margin-text-1
      - radioitem view-editpanel-margin-text-2
      - radioitem view-editpanel-margin-text-3
      - radioitem view-editpanel-margin-text-4
      - radioitem view-editpanel-margin-text-6
      - radioitem view-editpanel-margin-text-8
      - radioitem view-editpanel-margin-text-10
      - radioitem view-editpanel-margin-text-12

searchbar_contextmenu:
  - checkitem search-attribute-incremental-switch
  - checkitem search-attribute-autowrap-switch
  -
  - checkitem search-attribute-regex-switch
  - checkitem search-attribute-match-whole-word-switch
  - checkitem search-attribute-match-word-begin-switch
  - checkitem search-attribute-match-case-switch
  -
  - radioitem search-range-selection
  - radioitem search-range-document
  - radioitem search-range-open-docs

status_syntaxstyle_contextmenu:
  - checkitem document-syntaxmode-c
  - checkitem document-syntaxmode-conf
  - checkitem document-syntaxmode-css
  - checkitem document-syntaxmode-html
  - checkitem document-syntaxmode-js
  - checkitem document-syntaxmode-perl
  - checkitem document-syntaxmode-xml
  - checkitem document-syntaxmode-yaml
  -
  - item document-syntaxmode-auto
  - checkitem document-syntaxmode-none

status_whitespace_contextmenu:
  - checkitem tool-auto-indention
  - checkitem tool-brace-indention
  -
  - checkitem view-editpanel-whitespace
  -
    menu document_tab_width:
      - radioitem document-tabs-width-1
      - radioitem document-tabs-width-2
      - radioitem document-tabs-width-3
      - radioitem document-tabs-width-4
      - radioitem document-tabs-width-5
      - radioitem document-tabs-width-6
      - radioitem document-tabs-width-8
  -
    menu document_convert:
      - item edit-document-convert-tabs2spaces
      - item edit-document-convert-spaces2tabs
      -
      - item edit-document-convert-indent2spaces
      - item edit-document-convert-indent2tabs
      -
      - item edit-document-format-del-trailing-whitespace
  -
  - radioitem document-tabs-soft
  - radioitem document-tabs-hard

status_lineendchar_contextmenu:
  - checkitem view-editpanel-indicator-EOL
  -
  - item document-EOL-auto
  -
  - radioitem document-EOL-lf
  - radioitem document-EOL-cr
  - radioitem document-EOL-cr+lf

status_info_contexmenu:
  - radioitem view-statusbar-info-none
  - radioitem view-statusbar-info-length
  - radioitem view-statusbar-info-date
