language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.16"
  - "5.10"
before_script:
  - mysql -e 'CREATE DATABASE ipc_concurrency_dbi;'
  - psql -c 'CREATE DATABASE ipc_concurrency_dbi;' -U postgres
  - cpanm --notest DBI
  - cpanm --notest DBD::Pg
  - cpanm --notest DBD::mysql
env:
  - IPC_CONCURRENCY_DBI_DATABASE=''
  - IPC_CONCURRENCY_DBI_DATABASE='DBI:mysql:database=ipc_concurrency_dbi;host=127.0.0.1|root|'
  - IPC_CONCURRENCY_DBI_DATABASE='DBI:Pg:dbname=ipc_concurrency_dbi;host=127.0.0.1|postgres|'
before_install:
  cpanm -n Devel::Cover::Report::Coveralls
script:
  perl Build.PL && ./Build build && cover -test -report coveralls
