sudo: required
addons:
  hosts:
    - travis1.local
    - travis1
    - etcd1
env:
  global:
    - PATH=$PATH:/tmp/test-etcd/
    - ETCD_VER=v3.3.3
    - ETCDCTL_API=3
    - ETCD_TEST_HOST=etcd1
    - ETCD_TEST_PORT=2379
    - RELEASE_TESTING=1
    - ETCD_NAME=member1
    - ETCD_DEBUG=1
    - ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
    - ETCD_ADVERTISE_CLIENT_URLS=https://etcd1:2379
    - ETCD_INITIAL_ADVERTISE_PEER_URLS=https://etcd1:2380
    - ETCD_LISTEN_PEER_URLS=https://etcd1:2380
    - ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
    - ETCD_PEER_KEY_FILE=${TRAVIS_BUILD_DIR}/t/tls/etcd1-key.pem
    - ETCD_PEER_CERT_FILE=${TRAVIS_BUILD_DIR}/t/tls/etcd1.pem
    - ETCD_CERT_FILE=${TRAVIS_BUILD_DIR}/t/tls/server.pem
    - ETCD_KEY_FILE=${TRAVIS_BUILD_DIR}/t/tls/server-key.pem
    - ETCD_TRUSTED_CA_FILE=${TRAVIS_BUILD_DIR}/t/tls/ca.pem
    - ETCD_CLIENT_CERT_FILE=${TRAVIS_BUILD_DIR}/t/tls/client.pem
    - ETCD_CLIENT_KEY_FILE=${TRAVIS_BUILD_DIR}/t/tls/client-key.pem
    - ETCD_CLIENT_CA_FILE=${TRAVIS_BUILD_DIR}/t/tls/ca.pem
    - ETCD_PEER_CLIENT_CERT_AUTH=1
language: perl
perl:
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
matrix:
  include:
    - perl: 5.24
      env: COVERAGE=1   # enables coverage+coveralls reporting
before_install:
  - curl https://coreos.com/dist/pubkeys/app-signing-pubkey.gpg | sudo apt-key add -
  - wget https://github.com/coreos/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -O /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
  - mkdir -p /tmp/test-etcd
  - tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/test-etcd --strip-components=1
  - /tmp/test-etcd/etcd -version
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install --deps
  - cpan-install --coverage
script:
  - /tmp/test-etcd/etcd &
  - sleep 3
  - perl Makefile.PL
  - make
  - make test 
