site_name: 'Convert-Pheno Documentation'
site_description: 'Convert-Pheno Toolkit Documentation'
site_author: 'Manuel Rueda, PhD'
copyright: '&copy; Copyright 2022-2026, Manuel Rueda, CNAG'
repo_name: 'Convert-Pheno'
repo_url: https://github.com/mrueda/convert-pheno
edit_uri: edit/main/docs/
extra_css:
  - css/theme_overrides.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - js/theme_overrides.js
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

plugins:
  - search
  - macros
#  - external-markdown
  - mermaid2:
      arguments:
        startOnLoad: true

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: CNAG-Biomedical-Informatics
        repo: convert-pheno
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        base_path: docs
        url_download: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.arithmatex:
        generic: true

nav:
  - "ğŸ  Introduction":
      - "â“ What is Convert-Pheno?": what-is-convert-pheno.md
      - "ğŸ“‚ Supported formats": supported-formats.md
  - "â¬‡ï¸ Download & Installation": download-and-installation.md
  - "ğŸ›  Use":
      - "ğŸ’» As a command-line interface": use-as-a-command-line-interface.md
      - "ğŸ“¦ As a module": use-as-a-module.md
      - "ğŸ”— As an API": use-as-an-api.md
      - "ğŸŒ Web App User Interface": https://cnag-biomedical-informatics.github.io/convert-pheno-ui/
  - "ğŸ”„ Formats Accepted":
      - "ğŸ§¬ Beacon v2 Models (BFF)": bff.md
      - "ğŸ“¦ Phenopackets v2 (PXF)": pxf.md
      - "ğŸ“ REDCap": redcap.md
      - "ğŸ¥ OMOPâ€‘CDM": omop-cdm.md
      - "ğŸ“‘ CDISCâ€‘ODM": cdisc-odm.md
      - "ğŸ“Š CSV": csv.md
  - "âš™ï¸ Technical Details":
      - "ğŸ— Implementation": implementation.md
      - "ğŸ” Mapping Steps": mapping-steps.md
      - "ğŸ“Š Mapping Tables":
          - "ğŸ”„ OMOP to BFF": omop2bff.md
          - "ğŸ”„ PXF to BFF": pxf2bff.md
          - "ğŸ”„ BFF to PXF": bff2pxf.md
  - "â“ Help":
      - "ğŸ“ Tutorial": tutorial.md
      - "ğŸ“– Google Colab": https://colab.research.google.com/drive/1T6F3bLwfZyiYKD6fl1CIxs9vG068RHQ6
      - "ğŸ›  Usage": usage.md
      - "ğŸ¤” FAQs": faq.md
      - "ğŸ”® Future Plans": future-plans.md
  - "â„¹ï¸ About":
      - "ğŸ“„ About": about.md
      - "ğŸ“– Citation": citation.md
    # - Download PDF: pdf/beacon.pdf

theme:
  name: material
  #custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: img/CP-logo-grey.png
  icon:
      repo: fontawesome/brands/github-alt 
  features:
        - content.code.select
        - content.code.copy
        - content.tabs.link
        - search.highlight
        - search.share
        # - navigation.instant # otherwise blocks rendering of mermaid on page load
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mrueda

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
