name = "WebService-Mailgun"
badges = ["travis", "coveralls"]
module_maker = "ModuleBuildTiny"
markdown_maker = "Pod::Markdown::Github"
[FileGatherer]
exclude_match = ["Dockerfile", "docker-compose.yml"]
