name = "App-ansicolumn"
readme_from = "script/ansicolumn"
badges = ["travis-ci.com"]
authority="cpan:UTASHIRO"

module_maker="ModuleBuildTiny"
static_install = "auto"

[FileGatherer]
exclude_match=['^images/.*']
