name: Test install-doit-from-github action

on:
  push:
    paths:
      - '.github/workflows/*install-doit-from-github*'
      - '.github/actions/install-doit-from-github/**'
  workflow_dispatch:

jobs:
  test-install-doit-from-github:
    name: Test Doit.pm installation on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: eserte/Doit/.github/actions/install-doit-from-github@master
      - run: |
          perl -MDoit -MDoit::Log -E "info 'hello world'"

  test-install-doit-from-github-containers:
    name: Test Doit.pm installation on ${{ matrix.image }}
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      matrix:
        include:
          ## actions/checkout@v4 not compatible with stretch
          #- image: perl:5.8.9-threaded-stretch
          - image: perl:5.38.0-slim-bookworm
          - image: alpine:latest
          - image: fedora:38
          - image: debian:bookworm
          ## actions/checkout@v4 not compatible with centos:7
          #- image: centos:7
    steps:
      - run: |
          apk update -q && apk add -q perl
        if: startsWith(matrix.image, 'alpine:')
      - run: |
          apt-get update -q && apt-get install -qy perl
        if: startsWith(matrix.image, 'debian:')
      - run: |
          dnf update --quiet -y && dnf install --quiet -y perl
        if: startsWith(matrix.image, 'fedora:')
      - uses: eserte/Doit/.github/actions/install-doit-from-github@master
      - run: |
          perl -MDoit -MDoit::Log -E "info 'hello world'"
