name = "Getopt-EX-Hashed"
badges = [ 'github-actions/test', 'metacpan' ]
authority = "cpan:UTASHIRO"

module_maker = "ModuleBuildTiny"
static_install = "auto"

[FileGatherer]
exclude_match = [
    '^CLAUDE\.md$'
]

[release]
branch = "main"
hooks = [
    "make -C docs",
]
do_not_upload_to_cpan = 0

