site_name: 'Pheno-Ranker Documentation'
site_description: 'Pheno-Ranker Documentation'
site_author: 'Manuel Rueda, PhD'
copyright: '&copy; Copyright 2023-2025, Manuel Rueda, CNAG'
repo_name: 'Pheno-Ranker'
repo_url: https://github.com/mrueda/pheno-ranker
edit_uri: edit/main/docs/

extra_css: 
  - css/theme_overrides.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
  - js/theme_overrides.js
  - js/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/cytoscape/3.23.0/cytoscape.min.js
  - js/cytoscape-render.js

plugins:
  - search
  - macros
  - mermaid2:
      arguments:
        startOnLoad: true

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: CNAG-Biomedical-Informatics
        repo: pheno-ranker
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets:
        base_path: docs
        url_download: true
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid
    - pymdownx.arithmatex:
        generic: true

nav:
  - "ğŸ  Introduction":
      - "â“ What is Pheno-Ranker?": what-is-pheno-ranker.md
      - "ğŸ“‚ Input formats":
          - "ğŸ—‚ BFF": bff.md
          - "ğŸ“œ PXF": pxf.md
          - "ğŸ”„ Other formats": other-formats.md
  - "â¬‡ï¸ Download & Installation": download-and-installation.md
  - "ğŸŒ Web App User Interface": https://pheno-ranker.cnag.eu
  - "âš™ï¸ Modes of operation":
      - "ğŸ“Š Cohort mode": cohort.md 
      - "ğŸ‘¤ Patient mode": patient.md
  - "ğŸ›  Technical details":
      - "ğŸ— Implementation": implementation.md
      - "ğŸ“Š Algorithm": algorithm.md
      - "ğŸ§­ User workflow": user-workflow.md
  - "ğŸ§° Utilities":
      - "ğŸ“ˆ BFF/PXF plot": bff-pxf-plot.md 
      - "ğŸ§ª BFF/PXF simulator": bff-pxf-simulator.md
      - "ğŸ“‘ CSV import": csv-import.md
      - "ğŸ”² QR code generator": qr-code-generator.md
  - "ğŸš€ Use Cases":
      - "ğŸ¥ Phenopacket Corpus": phenopackets-corpus.md
      - "ğŸ§¬ OMIM Database": omim-database.md
  - "ğŸ”— Formats Beyond BFF/PXF": 
      - "ğŸ“œ Generic JSON": generic-json.md
      - "ğŸ“‘ CSV": csv-import.md
      - "ğŸ¥ openEHR": open-ehr.md
      - "ğŸ—„ OMOP-CDM": omop-cdm.md 
      - "ğŸ§¬ VCF": vcf.md
  - "â“ Help":
      - "ğŸ“– Google Colab": https://colab.research.google.com/drive/1n3Etu4fnwuDWNveSMb1SzuN50O2a05Rg#scrollTo=8tbJ0f5-hJAB
      - "ğŸ›  Usage": usage.md
      - "ğŸ¤” FAQs": faq.md
  - "ğŸ— Addendum":
      - "ğŸ”„ Federated version proposal": federated-version-proposal.md
  - "â„¹ï¸ About":  # âœ… Now collapsed until clicked!
      - "ğŸ“„ About": about.md
      - "ğŸ“– Citation": citation.md

theme:
  name: material
  #custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: img/iconhex.svg
  favicon: img/favicon-2x.png
  icon:
      repo: fontawesome/brands/github-alt 
  features:
        - content.code.select
        - content.code.copy
        - content.tabs.link
        - search.highlight
        - search.share
        # - navigation.instant # otherwise blocks rendering of mermaid on page load
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mrueda
