name = "LibUI"
badges = ["github-actions/linux.yaml", "github-actions/windows.yaml", "github-actions/osx.yaml", "github-actions/freebsd.yaml", "metacpan"]
authority="cpan:SANKO"
module_maker="ModuleBuildTiny"
static_install = "auto"
license = "artistic_2"