name = "Contextual-Diag"
badges = ["github-actions/test", "coveralls", "metacpan"]
authority="cpan:KFLY"

module_maker="ModuleBuildTiny"
static_install = "auto"
markdown_maker = "Pod::Markdown::Github"

[release]
branch = "main"
