language: perl
os:
  - linux
#  - osx    #doesnâ€™t install the correct perl
perl:
  - "5.32"
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
#  - "5.8"
#  - "5.6"
before_install:
    - "sudo apt-get install libunbound-dev"
    - eval $(curl https://travis-perl.github.io/init) --auto
    - "[ $TRAVIS_PERL_VERSION != '5.14' ] && [ $TRAVIS_PERL_VERSION != '5.12' ] && [ $TRAVIS_PERL_VERSION != '5.10' ] && cpanm --notest --verbose AnyEvent AnyEvent::XSPromises ||:"
    - cpanm --notest --verbose Promise::XS
    - cpanm --notest ExtUtils::MakeMaker
install:
    - cpanm --verbose --installdeps --notest .
jobs:
  include:
    - os: osx
      perl: system
      addons:
        homebrew:
          packages:
            - unbound
          # update: true
      before_install:
        - "curl -L http://cpanmin.us | perl - --self-upgrade"
        - export PATH=$PATH:$HOME/perl5/bin
        - "cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)"
