name = "Liveman"

authority="cpan:DART"
license="gpl_3"

badges = ["github-actions/test.yml", "metacpan"]
markdown_maker = "Liveman::MinillaPod2Markdown"
module_maker="ModuleBuildTiny"
static_install = "auto"
