name = "Linux-TempFile"
license = "perl_5"
module_maker="ModuleBuild"
[build]
build_class = "builder::MyBuilder"
[no_index]
directory = ['t', 'xt', 'inc', 'share', 'eg', 'examples', 'author', 'builder', 'vendor']
