name = "Mojolicious-Plugin-Text-Caml"
badges = ["metacpan", "travis", "coveralls"]
authority="cpan:CYNOVG"
module_maker="ModuleBuildTiny"
license="lgpl_3_0"
[release]
pause_config = "/home/cynovg/.pause"
