name = "Test-BDD-Cucumber-Definitions"
license="perl_5"
module_maker="ModuleBuildTiny"
badges = ["travis", "metacpan"]

[FileGatherer]
include_dotfiles = true
exclude_match = ['^\.(?!perlcriticrc|perltidyrc)']
