# SPDX-FileCopyrightText: Peter Pentchev <roam@ringlet.net>
# SPDX-License-Identifier: Artistic-2.0

name = "MooX-Role-CloneSet"
authority = "cpan:ROAM"
license = "artistic_2"

module_maker="ModuleBuildTiny"

[no_index]
directory = [
  "t",
  "xt",
  "inc",
  "share",
  "eg",
  "examples",
  "author",
  "builder",
  "tools",
  "LICENSES",
]
