#layout: "main"
#environment: development
appname: "CPAN::Digger::WWW"
logger: "file"
#logger: 'console'
template: template_toolkit
#daemon: 0  # setting to 1 does not do anything on Windows?
charset: utf-8
engines:
  template_toolkit:
    start_tag: '[%'
    stop_tag: '%]'
#plack_middlewares:
#  -
#    - Runtime
