language: perl

install:
  - curl https://perl5-alien.github.io/static/travis/install-system-dontpanic.sh | bash -
  - curl https://perl5-alien.github.io/static/travis/install-system-acme-alien-dontpanic.sh | bash -
  - cpanm --installdeps -n .

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - perl Build.PL
  - ./Build
  - ./Build test verbose=1

env:
  global:
    - PATH=$PATH:$HOME/opt/dontpanic/current/bin
    - LD_LIBRARY_PATH=$HOME/opt/dontpanic/current/lib
    - PKG_CONFIG_PATH=$HOME/opt/dontpanic/current/lib/pkgconfig
  matrix:
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_INSTALL_TYPE=system

  
