LCFG_NAME: name
LCFG_FULLNAME: fullname
LCFG_ABSTRACT: abstract
LCFG_VERSION: version
LCFG_PERL_VERSION: perl_version
LCFG_RELEASE: release
LCFG_SCHEMA: schema
LCFG_VENDOR: vendor
LCFG_GROUP: group
LCFG_AUTHOR: author
LCFG_PLATFORMS: platforms
LCFG_DATE: date
LCFG_TARNAME: tarname
LCFG_LICENSE: license
COMP: name
NAME: fullname
DESCR: abstract
V: version
VERSION: version
R: release
RELEASE: release
SCHEMA: schema
VENDOR: vendor
ORGANIZATION: vendor
GROUP: group
AUTHOR: author
PLATFORMS: platforms
DATE: date
TARFILE: tarname
CPACK_PACKAGE_DESCRIPTION_SUMMARY: abstract
CPACK_PACKAGE_VERSION: version
CPACK_RPM_PACKAGE_RELEASE: release
CPACK_RPM_PACKAGE_VENDOR: vendor
CPACK_RPM_PACKAGE_GROUP: group
CPACK_PACKAGE_CONTACT: author
CPACK_PACKAGE_VERSION_MAJOR: get_major
CPACK_PACKAGE_VERSION_MINOR: get_minor
CPACK_PACKAGE_VERSION_PATCH: get_micro
DEB_DSCNAME: deb_dscname
DEB_NAME: deb_name
DEB_SRCTARNAME: deb_srctarname
DEB_TARNAME: deb_tarname
DEB_VERSION: deb_version
