name = "Aion"

authority="cpan:DART"
license="gpl_3"

markdown_maker = "Liveman::MinillaPod2Markdown"
module_maker="ModuleBuildTiny"
static_install = "auto"

[unsupported]
os = [
    "MSWin32",
    "amigaos",
    "os2",
    "symbian",
    "dos",
    "VMS",
    "VOS",
    "riscos",
    "MacOS",
    "vmesa"
]
