exclude = [
    ".build/**/*",
    "Dist-Zilla-PluginBundle-DROLSKY-*/**/*",
    "META.yml",
    "MYMETA.yml",
    "blib/**/*",
    "t/00-*",
    "t/author-*",
    "t/release-*",
    "t/zzz-*",
    "xt/**/*",
]

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = ["omegasort", "--sort", "path", "--unique"]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1

[commands.omegasort-stopwords]
type = "both"
include = ".stopwords"
cmd = ["omegasort", "--sort", "text", "--case-insensitive", "--locale", "en-US", "--unique"]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1

[commands.perlcritic]
type = "lint"
include = ["**/*.{pl,pm,t,psgi}"]
cmd = ["perlcritic", "--profile=$PRECIOUS_ROOT/perlcriticrc"]
ok_exit_codes = 0
lint_failure_exit_codes = 2

[commands.perltidy]
type = "both"
include = ["**/*.{pl,pm,t,psgi}"]
cmd = ["perltidy", "--profile=$PRECIOUS_ROOT/perltidyrc"]
lint_flags = ["--assert-tidy", "--no-standard-output", "--outfile=/dev/null"]
tidy_flags = ["--backup-and-modify-in-place", "--backup-file-extension=/"]
ok_exit_codes = 0
lint_failure_exit_codes = 2
expect_stderr = true

[commands.podchecker]
type = "lint"
include = ["**/*.{pl,pm,pod}"]
exclude = "tools/templates/*.pod"
cmd = ["podchecker", "--warnings", "--warnings"]
ok_exit_codes = [0, 2]
lint_failure_exit_codes = 1
expect_stderr = true

[commands.podtidy]
type = "tidy"
include = ["**/*.{pl,pm,pod}"]
exclude = "tools/templates/*.pod"
cmd = ["podtidy", "--columns", "80", "--inplace", "--nobackup"]
ok_exit_codes = 0
lint_failure_exit_codes = 1

[commands.prettier]
type = "both"
include = ["**/*.yml"]
exclude = "META.yml"
cmd = ["prettier", "--no-config", "--prose-wrap", "always", "--print-width", "100"]
lint_flags = "--check"
tidy_flags = "--write"
ok_exit_codes = 0
lint_failure_exit_codes = 1
ignore_stderr = "Code style issues"

[commands.taplo]
type = "both"
include = "**/*.toml"
cmd = ["taplo", "format", "--option", "indent_string=    ", "--option", "column_width=100"]
lint_flags = "--check"
ok_exit_codes = 0
lint_failure_exit_codes = 1
ignore_stderr = "INFO taplo.+"
