name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        cip:
          - tag: "5.41"
          - tag: "5.40"
          - tag: "5.38"
          - tag: "5.38-alpine3.16"
          - tag: "5.38-fedora36"
          - tag: "5.36"
          - tag: "5.34"
          - tag: "5.32"
          - tag: "5.30"
          - tag: "5.28"
          - tag: "5.26"
          - tag: "5.24"
          - tag: "5.22"
          - tag: "5.20"
          - tag: "5.18"
          - tag: "5.16"
          - tag: "5.14"
          - tag: "5.12"
          - tag: "5.10"
          - tag: "5.8"

    env:
      CIP_TAG: ${{ matrix.cip.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap CIP
        run: |
          curl -L https://raw.githubusercontent.com/uperl/cip/main/bin/github-bootstrap | bash

      - name: Cache-Key
        id: cache-key
        run: |
          echo -n '::set-output name=key::'
          cip cache-key

      - name: Cache CPAN modules
        uses: actions/cache@v4
        with:
          path: ~/.cip
          key: ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}
          restore-keys: |
            ${{ runner.os }}-build-${{ steps.cache-key.outputs.key }}

      - name: Start-Container
        run: |
          cip start

      - name: Diagnostics
        run: |
          cip diag

      - name: Install-Dependencies
        run: |
          cip install

      - name: Build + Test
        run: |
          cip script

      - name: CPAN log
        if: ${{ failure() }}
        run: |
          cip exec bash -c 'cat $HOME/.cpanm/latest-build/build.log'
